#!/usr/bin/env bash
#configure an nginx server to listen on port 80

#creates a symbolic link (-s option) between the nginx configuration file
#and the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
service nginx restart
#terminates the first nginx process ID
kill "$(grep 'nginx' | head -1)"
